name: NPM Publish on Release

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.target_commitish }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org/'
          cache: 'yarn'

      - name: Verify package version matches release tag
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          RELEASE_TAG="${{ github.event.release.tag_name }}"
          RELEASE_VERSION="${RELEASE_TAG#v}"
          if [ "$PACKAGE_VERSION" != "$RELEASE_VERSION" ]; then
            echo "Error: Package version ($PACKAGE_VERSION) does not match release tag ($RELEASE_VERSION)"
            exit 1
          fi

      - name: Install dependencies 
        run: yarn install --frozen-lockfile

      - name: Build package
        run: yarn build

      - name: Publish to NPM
        run: yarn publish --non-interactive
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}