name: NPM Publish on Release

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.target_commitish }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies 
        run: yarn install --frozen-lockfile

      - name: Build package
        run: yarn build

      - name: Set version from release
        run: |
          VERSION="${{ github.event.release.tag_name }}"
          # Remove 'v' prefix if present
          VERSION=${VERSION#v}
          echo "Setting version to $VERSION"
          npm version $VERSION --no-git-tag-version

      - name: Determine npm tag
        id: npm_tag
        run: |
          if [[ "${{ github.event.release.tag_name }}" == *"-alpha"* ]]; then
            echo "tag=alpha" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.release.tag_name }}" == *"-beta"* ]]; then
            echo "tag=beta" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.release.tag_name }}" == *"-rc"* ]]; then
            echo "tag=rc" >> $GITHUB_OUTPUT
          else
            echo "tag=latest" >> $GITHUB_OUTPUT
          fi

      - name: Publish to NPM
        run: npm publish --tag ${{ steps.npm_tag.outputs.tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}